# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: HouseRentingBuildAndTest.NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v4
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./House-Renting-System-App/HouseRentingSystem.sln
      
    - name: Build Application
      run: dotnet build --no-restore ./House-Renting-System-App/HouseRentingSystem.sln
      
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal ./House-Renting-System-App/HouseRentingSystem.sln
